import { calcInningsStats, getBatsmenList, getBowlersList, getBatsmanStats, getBowlerStats } from './cricketCalc.js'

/**
 * Generate a plain-text scorecard for sharing via Web Share API.
 * @param {Object} match  MatchObject
 * @returns {string}
 */
export function generateShareText(match) {
  if (!match) return ''

  const lines = []
  lines.push('🏏 TURF CRICKET SCORECARD')
  lines.push(`📅 ${match.date}`)
  lines.push(`${match.team1} vs ${match.team2}  |  ${match.overs} overs`)
  lines.push('─'.repeat(36))

  match.innings.forEach((inn, idx) => {
    if (!inn.balls.length) return
    const stats = calcInningsStats(inn.balls)
    lines.push(`\n${inn.battingTeam} — ${stats.runs}/${stats.wickets} (${stats.overs}.${stats.ballsInOver} ov)`)
    lines.push('')

    // Batting
    lines.push('BATTING')
    const batsmen = getBatsmenList(inn.balls)
    batsmen.forEach(name => {
      const s = getBatsmanStats(inn.balls, name)
      const status = s.isOut ? s.howOut : 'not out'
      lines.push(`  ${name.padEnd(16)} ${String(s.runs).padStart(3)}  (${s.ballsFaced}b)  ${status}`)
    })
    lines.push(`  Extras: W:${stats.wides} NB:${stats.noBalls} B:${stats.byes} LB:${stats.legByes}`)
    lines.push(`  Total: ${stats.runs}/${stats.wickets}  RR: ${stats.rr}`)

    lines.push('')
    lines.push('BOWLING')
    const bowlers = getBowlersList(inn.balls)
    bowlers.forEach(name => {
      const s = getBowlerStats(inn.balls, name)
      lines.push(`  ${name.padEnd(16)} ${s.oversStr}  ${String(s.runs).padStart(3)}  ${s.wickets}W  Eco:${s.eco}`)
    })
  })

  lines.push('\n─'.repeat(36))
  if (match.winner && match.winner !== 'Tie') {
    lines.push(`🏆 ${match.winner} won by ${match.margin}`)
  } else if (match.winner === 'Tie') {
    lines.push('🤝 Match Tied!')
  }
  lines.push('\nGenerated by Turf Cricket PWA')

  return lines.join('\n')
}

/**
 * Trigger the Web Share API with a text scorecard.
 * @param {Object} match
 * @returns {Promise<void>}
 */
export async function shareScorecard(match) {
  const text = generateShareText(match)
  if (navigator.share) {
    await navigator.share({
      title: `${match.team1} vs ${match.team2} — Turf Cricket`,
      text,
    })
  } else {
    await navigator.clipboard.writeText(text)
  }
}
